# Generated by Django 4.1.8 on 2023-05-03 07:56

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='single_project/demo_1.png', upload_to='projects/', validators=[projects.models.Project.validate_image]),
        ),
    ]
